#!/bin/bash
# Quick start guide for testing offline AquaSphere

echo "🌐 AquaSphere Offline Testing Guide"
echo "===================================="
echo ""
echo "Step 1: Start the Flask app"
echo "  cd c:\Users\bhoge\OneDrive\Documents\Desktop\AQUA"
echo "  python app.py"
echo ""
echo "Step 2: Open in browser"
echo "  http://localhost:5000"
echo ""
echo "Step 3: Let datasets load (first visit only)"
echo "  - DevTools → Application → IndexedDB → AquaSphereDB"
echo "  - You'll see: disease, location, feed, yield, buyer, stocking, seed"
echo ""
echo "Step 4: Test offline"
echo "  - DevTools → Application → Service Workers"
echo "  - Check 'Offline' checkbox"
echo "  - Try prediction forms (they'll work!)"
echo ""
echo "Step 5: Check offline status"
echo "  http://localhost:5000/offline-status"
echo "  - Shows cached datasets"
echo "  - Shows synced predictions"
echo ""
echo "Step 6: Go back online"
echo "  - Uncheck 'Offline' in Service Workers"
echo "  - You'll see notification: '🌐 You are back online!'"
echo "  - Predictions automatically sync"
echo ""
echo "✅ Done! Your app now works offline!"
