
import json
import re

def fix_tamil():
    try:
        with open('patch_fix_tamil.json', 'r', encoding='utf-8') as f:
            patch_data = json.load(f)
            tamil_data = patch_data.get('ta', {})
    except Exception as e:
        print(f"Error reading patch file: {e}")
        return

    with open('translations.py', 'r', encoding='utf-8') as f:
        lines = f.readlines()
 
    new_lines = []
    inside_tamil = False
    
    # Simple state machine to completely replace the 'ta' block
    # This assumes standard formatting as generated by previous scripts
    
    lang_start_re = re.compile(r"^\s+'([a-z]{2})': \{")
    
    for line in lines:
        match = lang_start_re.match(line)
        if match:
            lang = match.group(1)
            if lang == 'ta':
                inside_tamil = True
                # Start writing new block
                new_lines.append(f"    'ta': {{\n")
                for k, v in tamil_data.items():
                    val_escaped = v.replace("'", "\\'")
                    new_lines.append(f"        '{k}': '{val_escaped}',\n")
                new_lines.append("    },\n")
                continue
            else:
                inside_tamil = False
        
        if inside_tamil:
            # Skip old tamil lines until we hit the closing brace of that block
            if line.strip() == '},':
                inside_tamil = False
            continue
            
        new_lines.append(line)

    with open('translations.py', 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
        
    print("Fixed Tamil translations.")

if __name__ == "__main__":
    fix_tamil()
